/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/util/events';
import * as import9 from '../providers/user-data';
import * as import10 from 'ionic-angular/components/menu/menu-controller';
import * as import11 from 'ionic-angular/platform/platform';
import * as import12 from '../providers/conference-data';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import17 from '../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import18 from '../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import19 from '../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import20 from '../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import21 from '../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import22 from '../node_modules/ionic-angular/components/list/list-header.ngfactory';
import * as import23 from '../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import24 from '../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from 'ionic-angular/util/keyboard';
import * as import28 from '@angular/core/src/zone/ng_zone';
import * as import29 from 'ionic-angular/gestures/gesture-controller';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from 'ionic-angular/components/navbar/navbar';
import * as import32 from 'ionic-angular/components/app/app';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from 'ionic-angular/util/form';
import * as import35 from '@angular/core/src/linker/template_ref';
import * as import36 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import37 from 'ionic-angular/navigation/nav-controller-base';
import * as import38 from '@angular/core/src/linker/component_factory_resolver';
import * as import39 from 'ionic-angular/transitions/transition-controller';
import * as import40 from 'ionic-angular/navigation/deep-linker';
import * as import41 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import42 from 'ionic-angular/components/toolbar/toolbar';
import * as import43 from 'ionic-angular/components/item/item';
import * as import44 from 'ionic-angular/components/list/list-header';
import * as import45 from '@angular/common/src/directives/ng_for';
import * as import46 from 'ionic-angular/components/list/list';
import * as import47 from 'ionic-angular/components/content/content';
import * as import48 from 'ionic-angular/components/menu/menu';
import * as import49 from 'ionic-angular/components/nav/nav';
import * as import50 from '../node_modules/ionic-angular/components/menu/menu-close.ngfactory';
import * as import51 from '../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import52 from 'ionic-angular/components/icon/icon';
import * as import53 from 'ionic-angular/components/menu/menu-close';
export class Wrapper_ConferenceApp {
  context:import0.ConferenceApp;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.ConferenceApp(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ConferenceApp_Host:import2.RenderComponentType = (null as any);
class _View_ConferenceApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ConferenceApp_0_4:Wrapper_ConferenceApp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConferenceApp_Host0,renderType_ConferenceApp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ConferenceApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ConferenceApp_0_4 = new Wrapper_ConferenceApp(this.parentInjector.get(import8.Events),this.parentInjector.get(import9.UserData),this.parentInjector.get(import10.MenuController),this.parentInjector.get(import11.Platform),this.parentInjector.get(import12.ConferenceData));
    this._appEl_0.initComponent(this._ConferenceApp_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ConferenceApp_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ConferenceApp) && (0 === requestNodeIndex))) { return this._ConferenceApp_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ConferenceApp_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ConferenceApp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ConferenceApp_Host === (null as any))) { (renderType_ConferenceApp_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ConferenceApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const ConferenceAppNgFactory:import14.ComponentFactory<import0.ConferenceApp> = new import14.ComponentFactory<import0.ConferenceApp>('ng-component',viewFactory_ConferenceApp_Host0,import0.ConferenceApp);
const styles_ConferenceApp:any[] = ([] as any[]);
var renderType_ConferenceApp:import2.RenderComponentType = (null as any);
class _View_ConferenceApp0 extends import1.AppView<import0.ConferenceApp> {
  _viewQuery_Nav_0:import15.QueryList<any>;
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import3.AppElement;
  _Menu_1_4:import16.Wrapper_Menu;
  _query_Content_1_0:import15.QueryList<any>;
  _text_2:any;
  _el_3:any;
  _Header_3_3:import17.Wrapper_Header;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Toolbar_5_4:import17.Wrapper_Toolbar;
  _text_6:any;
  _el_7:any;
  /*private*/ _appEl_7:import3.AppElement;
  _ToolbarTitle_7_4:import18.Wrapper_ToolbarTitle;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  /*private*/ _appEl_12:import3.AppElement;
  _Content_12_4:import19.Wrapper_Content;
  _text_13:any;
  _el_14:any;
  _List_14_3:import20.Wrapper_List;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _Item_16_4:import21.Wrapper_Item;
  _ListHeader_16_5:import22.Wrapper_ListHeader;
  _query_Label_16_0:import15.QueryList<any>;
  _query_Button_16_1:import15.QueryList<any>;
  _query_Icon_16_2:import15.QueryList<any>;
  _text_17:any;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _TemplateRef_19_5:any;
  _NgFor_19_6:import23.Wrapper_NgFor;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _List_22_3:import20.Wrapper_List;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _Item_24_4:import21.Wrapper_Item;
  _ListHeader_24_5:import22.Wrapper_ListHeader;
  _query_Label_24_0:import15.QueryList<any>;
  _query_Button_24_1:import15.QueryList<any>;
  _query_Icon_24_2:import15.QueryList<any>;
  _text_25:any;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _TemplateRef_27_5:any;
  _NgFor_27_6:import23.Wrapper_NgFor;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  /*private*/ _appEl_33:import3.AppElement;
  _Menu_33_4:import16.Wrapper_Menu;
  _query_Content_33_0:import15.QueryList<any>;
  _text_34:any;
  _el_35:any;
  _Header_35_3:import17.Wrapper_Header;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _Toolbar_37_4:import17.Wrapper_Toolbar;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import3.AppElement;
  _ToolbarTitle_39_4:import18.Wrapper_ToolbarTitle;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  /*private*/ _appEl_44:import3.AppElement;
  _Content_44_4:import19.Wrapper_Content;
  _text_45:any;
  _el_46:any;
  _List_46_3:import20.Wrapper_List;
  _text_47:any;
  _el_48:any;
  /*private*/ _appEl_48:import3.AppElement;
  _Item_48_4:import21.Wrapper_Item;
  _ListHeader_48_5:import22.Wrapper_ListHeader;
  _query_Label_48_0:import15.QueryList<any>;
  _query_Button_48_1:import15.QueryList<any>;
  _query_Icon_48_2:import15.QueryList<any>;
  _text_49:any;
  _text_50:any;
  _anchor_51:any;
  /*private*/ _appEl_51:import3.AppElement;
  _TemplateRef_51_5:any;
  _NgFor_51_6:import23.Wrapper_NgFor;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _List_54_3:import20.Wrapper_List;
  _text_55:any;
  _el_56:any;
  /*private*/ _appEl_56:import3.AppElement;
  _Item_56_4:import21.Wrapper_Item;
  _ListHeader_56_5:import22.Wrapper_ListHeader;
  _query_Label_56_0:import15.QueryList<any>;
  _query_Button_56_1:import15.QueryList<any>;
  _query_Icon_56_2:import15.QueryList<any>;
  _text_57:any;
  _text_58:any;
  _anchor_59:any;
  /*private*/ _appEl_59:import3.AppElement;
  _TemplateRef_59_5:any;
  _NgFor_59_6:import23.Wrapper_NgFor;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  /*private*/ _appEl_65:import3.AppElement;
  _Nav_65_4:import24.Wrapper_Nav;
  _text_66:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConferenceApp0,renderType_ConferenceApp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_Nav_0 = new import15.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_1,'id','loggedOutMenu');
    this.renderer.setElementAttribute(this._el_1,'role','navigation');
    this._appEl_1 = new import3.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import16.viewFactory_Menu0(this.viewUtils,this.injector(1),this._appEl_1);
    this._Menu_1_4 = new import16.Wrapper_Menu(this.parentInjector.get(import10.MenuController),new import25.ElementRef(this._el_1),this.parentInjector.get(import26.Config),this.parentInjector.get(import11.Platform),this.renderer,this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import29.GestureController));
    this._query_Content_1_0 = new import15.QueryList<any>();
    this._appEl_1.initComponent(this._Menu_1_4.context,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement((null as any),'ion-header',(null as any));
    this._Header_3_3 = new import17.Wrapper_Header(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_3),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','toolbar');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import17.viewFactory_Toolbar0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Toolbar_5_4 = new import17.Wrapper_Toolbar(this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_5),this.renderer);
    this._appEl_5.initComponent(this._Toolbar_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_7 = new import3.AppElement(7,5,this,this._el_7);
    var compView_7:any = import18.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(7),this._appEl_7);
    this._ToolbarTitle_7_4 = new import18.Wrapper_ToolbarTitle(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_7),this.renderer,this._Toolbar_5_4.context,this.parentInjector.get(import31.Navbar,(null as any)));
    this._appEl_7.initComponent(this._ToolbarTitle_7_4.context,([] as any[]),compView_7);
    this._text_8 = this.renderer.createText((null as any),'Menu',(null as any));
    compView_7.create(this._ToolbarTitle_7_4.context,[([] as any[]).concat([this._text_8])],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_5.create(this._Toolbar_5_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_6,
        this._el_7,
        this._text_9
      ]
      )
    ]
    ,(null as any));
    this._text_10 = this.renderer.createText(this._el_3,'\n  ',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','outer-content');
    this._appEl_12 = new import3.AppElement(12,1,this,this._el_12);
    var compView_12:any = import19.viewFactory_Content0(this.viewUtils,this.injector(12),this._appEl_12);
    this._Content_12_4 = new import19.Wrapper_Content(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_12),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_12.initComponent(this._Content_12_4.context,([] as any[]),compView_12);
    this._text_13 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_14_3 = new import20.Wrapper_List(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import29.GestureController));
    this._text_15 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','item');
    this._appEl_16 = new import3.AppElement(16,14,this,this._el_16);
    var compView_16:any = import21.viewFactory_Item0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Item_16_4 = new import21.Wrapper_Item(this.parentInjector.get(import34.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_16),this.renderer);
    this._ListHeader_16_5 = new import22.Wrapper_ListHeader(this.parentInjector.get(import26.Config),this.renderer,new import25.ElementRef(this._el_16),(null as any));
    this._query_Label_16_0 = new import15.QueryList<any>();
    this._query_Button_16_1 = new import15.QueryList<any>();
    this._query_Icon_16_2 = new import15.QueryList<any>();
    this._appEl_16.initComponent(this._Item_16_4.context,([] as any[]),compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n        Navigate\n      ',(null as any));
    this._query_Label_16_0.reset(([] as any[]));
    this._Item_16_4.context.contentLabel = this._query_Label_16_0.first;
    compView_16.create(this._Item_16_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_17]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n      ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._appEl_19 = new import3.AppElement(19,14,this,this._anchor_19);
    this._TemplateRef_19_5 = new import35.TemplateRef_(this._appEl_19,viewFactory_ConferenceApp1);
    this._NgFor_19_6 = new import23.Wrapper_NgFor(this._appEl_19.vcRef,this._TemplateRef_19_5,this.parentInjector.get(import36.IterableDiffers),this.ref);
    this._text_20 = this.renderer.createText(this._el_14,'\n    ',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_22_3 = new import20.Wrapper_List(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_22),this.renderer,this.parentInjector.get(import29.GestureController));
    this._text_23 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','item');
    this._appEl_24 = new import3.AppElement(24,22,this,this._el_24);
    var compView_24:any = import21.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import21.Wrapper_Item(this.parentInjector.get(import34.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_24),this.renderer);
    this._ListHeader_24_5 = new import22.Wrapper_ListHeader(this.parentInjector.get(import26.Config),this.renderer,new import25.ElementRef(this._el_24),(null as any));
    this._query_Label_24_0 = new import15.QueryList<any>();
    this._query_Button_24_1 = new import15.QueryList<any>();
    this._query_Icon_24_2 = new import15.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4.context,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n        Account\n      ',(null as any));
    this._query_Label_24_0.reset(([] as any[]));
    this._Item_24_4.context.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_25]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_22,(null as any));
    this._appEl_27 = new import3.AppElement(27,22,this,this._anchor_27);
    this._TemplateRef_27_5 = new import35.TemplateRef_(this._appEl_27,viewFactory_ConferenceApp2);
    this._NgFor_27_6 = new import23.Wrapper_NgFor(this._appEl_27.vcRef,this._TemplateRef_27_5,this.parentInjector.get(import36.IterableDiffers),this.ref);
    this._text_28 = this.renderer.createText(this._el_22,'\n    ',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_12.create(this._Content_12_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_13,
        this._el_14,
        this._text_21,
        this._el_22,
        this._text_29
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._query_Content_1_0.reset([this._Content_12_4.context]);
    this._Menu_1_4.context.menuContent = this._query_Content_1_0.first;
      compView_1.create(this._Menu_1_4.context,[([] as any[]).concat([
        this._text_2,
        this._el_3,
        this._text_11,
        this._el_12,
        this._text_30
      ]
    )],(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_32 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_33 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_33,'id','loggedInMenu');
    this.renderer.setElementAttribute(this._el_33,'role','navigation');
    this._appEl_33 = new import3.AppElement(33,(null as any),this,this._el_33);
    var compView_33:any = import16.viewFactory_Menu0(this.viewUtils,this.injector(33),this._appEl_33);
    this._Menu_33_4 = new import16.Wrapper_Menu(this.parentInjector.get(import10.MenuController),new import25.ElementRef(this._el_33),this.parentInjector.get(import26.Config),this.parentInjector.get(import11.Platform),this.renderer,this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import29.GestureController));
    this._query_Content_33_0 = new import15.QueryList<any>();
    this._appEl_33.initComponent(this._Menu_33_4.context,([] as any[]),compView_33);
    this._text_34 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'ion-header',(null as any));
    this._Header_35_3 = new import17.Wrapper_Header(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_35),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_36 = this.renderer.createText(this._el_35,'\n    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','toolbar');
    this._appEl_37 = new import3.AppElement(37,35,this,this._el_37);
    var compView_37:any = import17.viewFactory_Toolbar0(this.viewUtils,this.injector(37),this._appEl_37);
    this._Toolbar_37_4 = new import17.Wrapper_Toolbar(this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_37),this.renderer);
    this._appEl_37.initComponent(this._Toolbar_37_4.context,([] as any[]),compView_37);
    this._text_38 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_39 = new import3.AppElement(39,37,this,this._el_39);
    var compView_39:any = import18.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(39),this._appEl_39);
    this._ToolbarTitle_39_4 = new import18.Wrapper_ToolbarTitle(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_39),this.renderer,this._Toolbar_37_4.context,this.parentInjector.get(import31.Navbar,(null as any)));
    this._appEl_39.initComponent(this._ToolbarTitle_39_4.context,([] as any[]),compView_39);
    this._text_40 = this.renderer.createText((null as any),'Menu',(null as any));
    compView_39.create(this._ToolbarTitle_39_4.context,[([] as any[]).concat([this._text_40])],(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_37.create(this._Toolbar_37_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_38,
        this._el_39,
        this._text_41
      ]
      )
    ]
    ,(null as any));
    this._text_42 = this.renderer.createText(this._el_35,'\n  ',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','outer-content');
    this._appEl_44 = new import3.AppElement(44,33,this,this._el_44);
    var compView_44:any = import19.viewFactory_Content0(this.viewUtils,this.injector(44),this._appEl_44);
    this._Content_44_4 = new import19.Wrapper_Content(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_44),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import27.Keyboard),this.parentInjector.get(import28.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_44.initComponent(this._Content_44_4.context,([] as any[]),compView_44);
    this._text_45 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_46 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_46_3 = new import20.Wrapper_List(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_46),this.renderer,this.parentInjector.get(import29.GestureController));
    this._text_47 = this.renderer.createText(this._el_46,'\n      ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','item');
    this._appEl_48 = new import3.AppElement(48,46,this,this._el_48);
    var compView_48:any = import21.viewFactory_Item0(this.viewUtils,this.injector(48),this._appEl_48);
    this._Item_48_4 = new import21.Wrapper_Item(this.parentInjector.get(import34.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_48),this.renderer);
    this._ListHeader_48_5 = new import22.Wrapper_ListHeader(this.parentInjector.get(import26.Config),this.renderer,new import25.ElementRef(this._el_48),(null as any));
    this._query_Label_48_0 = new import15.QueryList<any>();
    this._query_Button_48_1 = new import15.QueryList<any>();
    this._query_Icon_48_2 = new import15.QueryList<any>();
    this._appEl_48.initComponent(this._Item_48_4.context,([] as any[]),compView_48);
    this._text_49 = this.renderer.createText((null as any),'\n        Navigate\n      ',(null as any));
    this._query_Label_48_0.reset(([] as any[]));
    this._Item_48_4.context.contentLabel = this._query_Label_48_0.first;
    compView_48.create(this._Item_48_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_49]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_50 = this.renderer.createText(this._el_46,'\n      ',(null as any));
    this._anchor_51 = this.renderer.createTemplateAnchor(this._el_46,(null as any));
    this._appEl_51 = new import3.AppElement(51,46,this,this._anchor_51);
    this._TemplateRef_51_5 = new import35.TemplateRef_(this._appEl_51,viewFactory_ConferenceApp3);
    this._NgFor_51_6 = new import23.Wrapper_NgFor(this._appEl_51.vcRef,this._TemplateRef_51_5,this.parentInjector.get(import36.IterableDiffers),this.ref);
    this._text_52 = this.renderer.createText(this._el_46,'\n    ',(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_54 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this._List_54_3 = new import20.Wrapper_List(this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_54),this.renderer,this.parentInjector.get(import29.GestureController));
    this._text_55 = this.renderer.createText(this._el_54,'\n      ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'ion-list-header',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','item');
    this._appEl_56 = new import3.AppElement(56,54,this,this._el_56);
    var compView_56:any = import21.viewFactory_Item0(this.viewUtils,this.injector(56),this._appEl_56);
    this._Item_56_4 = new import21.Wrapper_Item(this.parentInjector.get(import34.Form),this.parentInjector.get(import26.Config),new import25.ElementRef(this._el_56),this.renderer);
    this._ListHeader_56_5 = new import22.Wrapper_ListHeader(this.parentInjector.get(import26.Config),this.renderer,new import25.ElementRef(this._el_56),(null as any));
    this._query_Label_56_0 = new import15.QueryList<any>();
    this._query_Button_56_1 = new import15.QueryList<any>();
    this._query_Icon_56_2 = new import15.QueryList<any>();
    this._appEl_56.initComponent(this._Item_56_4.context,([] as any[]),compView_56);
    this._text_57 = this.renderer.createText((null as any),'\n        Account\n      ',(null as any));
    this._query_Label_56_0.reset(([] as any[]));
    this._Item_56_4.context.contentLabel = this._query_Label_56_0.first;
    compView_56.create(this._Item_56_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_57]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_58 = this.renderer.createText(this._el_54,'\n      ',(null as any));
    this._anchor_59 = this.renderer.createTemplateAnchor(this._el_54,(null as any));
    this._appEl_59 = new import3.AppElement(59,54,this,this._anchor_59);
    this._TemplateRef_59_5 = new import35.TemplateRef_(this._appEl_59,viewFactory_ConferenceApp4);
    this._NgFor_59_6 = new import23.Wrapper_NgFor(this._appEl_59.vcRef,this._TemplateRef_59_5,this.parentInjector.get(import36.IterableDiffers),this.ref);
    this._text_60 = this.renderer.createText(this._el_54,'\n    ',(null as any));
    this._text_61 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    compView_44.create(this._Content_44_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_45,
        this._el_46,
        this._text_53,
        this._el_54,
        this._text_61
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_62 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._query_Content_33_0.reset([this._Content_44_4.context]);
    this._Menu_33_4.context.menuContent = this._query_Content_33_0.first;
      compView_33.create(this._Menu_33_4.context,[([] as any[]).concat([
        this._text_34,
        this._el_35,
        this._text_43,
        this._el_44,
        this._text_62
      ]
    )],(null as any));
    this._text_63 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._text_64 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_65 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this.renderer.setElementAttribute(this._el_65,'swipeBackEnabled','false');
    this._appEl_65 = new import3.AppElement(65,(null as any),this,this._el_65);
    var compView_65:any = import24.viewFactory_Nav0(this.viewUtils,this.injector(65),this._appEl_65);
    this._Nav_65_4 = new import24.Wrapper_Nav(this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import37.NavControllerBase,(null as any)),this.parentInjector.get(import32.App),this.parentInjector.get(import26.Config),this.parentInjector.get(import27.Keyboard),new import25.ElementRef(this._el_65),this.parentInjector.get(import28.NgZone),this.renderer,this.parentInjector.get(import38.ComponentFactoryResolver),this.parentInjector.get(import29.GestureController),this.parentInjector.get(import39.TransitionController),this.parentInjector.get(import40.DeepLinker,(null as any)));
    this._appEl_65.initComponent(this._Nav_65_4.context,([] as any[]),compView_65);
    compView_65.create(this._Nav_65_4.context,([] as any[]),(null as any));
    this._text_66 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._viewQuery_Nav_0.reset([this._Nav_65_4.context]);
    this.context.nav = this._viewQuery_Nav_0.first;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._anchor_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._anchor_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.ToolbarTitle) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarTitle_7_4.context; }
    if (((token === import42.Toolbar) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Toolbar_5_4.context; }
    if (((token === import42.Header) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Header_3_3.context; }
    if (((token === import43.Item) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Item_16_4.context; }
    if (((token === import44.ListHeader) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._ListHeader_16_5.context; }
    if (((token === import35.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import45.NgFor) && (19 === requestNodeIndex))) { return this._NgFor_19_6.context; }
    if (((token === import46.List) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._List_14_3.context; }
    if (((token === import43.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Item_24_4.context; }
    if (((token === import44.ListHeader) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._ListHeader_24_5.context; }
    if (((token === import35.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import45.NgFor) && (27 === requestNodeIndex))) { return this._NgFor_27_6.context; }
    if (((token === import46.List) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._List_22_3.context; }
    if (((token === import47.Content) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Content_12_4.context; }
    if (((token === import48.Menu) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Menu_1_4.context; }
    if (((token === import41.ToolbarTitle) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._ToolbarTitle_39_4.context; }
    if (((token === import42.Toolbar) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Toolbar_37_4.context; }
    if (((token === import42.Header) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Header_35_3.context; }
    if (((token === import43.Item) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Item_48_4.context; }
    if (((token === import44.ListHeader) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._ListHeader_48_5.context; }
    if (((token === import35.TemplateRef) && (51 === requestNodeIndex))) { return this._TemplateRef_51_5; }
    if (((token === import45.NgFor) && (51 === requestNodeIndex))) { return this._NgFor_51_6.context; }
    if (((token === import46.List) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._List_46_3.context; }
    if (((token === import43.Item) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._Item_56_4.context; }
    if (((token === import44.ListHeader) && ((56 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._ListHeader_56_5.context; }
    if (((token === import35.TemplateRef) && (59 === requestNodeIndex))) { return this._TemplateRef_59_5; }
    if (((token === import45.NgFor) && (59 === requestNodeIndex))) { return this._NgFor_59_6.context; }
    if (((token === import46.List) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._List_54_3.context; }
    if (((token === import47.Content) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._Content_44_4.context; }
    if (((token === import48.Menu) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 62)))) { return this._Menu_33_4.context; }
    if (((token === import49.Nav) && (65 === requestNodeIndex))) { return this._Nav_65_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this._Nav_65_4.context;
    this._Menu_1_4.check_content(currVal_0,throwOnChange,false);
    const currVal_1:any = 'loggedOutMenu';
    this._Menu_1_4.check_id(currVal_1,throwOnChange,false);
    if (this._Menu_1_4.detectChangesInternal(this,this._el_1,throwOnChange)) { this._appEl_1.componentView.markAsCheckOnce(); }
    this._Header_3_3.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._Toolbar_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._ToolbarTitle_7_4.detectChangesInternal(this,this._el_7,throwOnChange)) { this._appEl_7.componentView.markAsCheckOnce(); }
    if (this._Content_12_4.detectChangesInternal(this,this._el_12,throwOnChange)) { this._appEl_12.componentView.markAsCheckOnce(); }
    this._List_14_3.detectChangesInternal(this,this._el_14,throwOnChange);
    if (this._Item_16_4.detectChangesInternal(this,this._el_16,throwOnChange)) { this._appEl_16.componentView.markAsCheckOnce(); }
    this._ListHeader_16_5.detectChangesInternal(this,this._el_16,throwOnChange);
    const currVal_4:any = this.context.appPages;
    this._NgFor_19_6.check_ngForOf(currVal_4,throwOnChange,false);
    this._NgFor_19_6.detectChangesInternal(this,this._anchor_19,throwOnChange);
    this._List_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    if (this._Item_24_4.detectChangesInternal(this,this._el_24,throwOnChange)) { this._appEl_24.componentView.markAsCheckOnce(); }
    this._ListHeader_24_5.detectChangesInternal(this,this._el_24,throwOnChange);
    const currVal_5:any = this.context.loggedOutPages;
    this._NgFor_27_6.check_ngForOf(currVal_5,throwOnChange,false);
    this._NgFor_27_6.detectChangesInternal(this,this._anchor_27,throwOnChange);
    const currVal_6:any = this._Nav_65_4.context;
    this._Menu_33_4.check_content(currVal_6,throwOnChange,false);
    const currVal_7:any = 'loggedInMenu';
    this._Menu_33_4.check_id(currVal_7,throwOnChange,false);
    if (this._Menu_33_4.detectChangesInternal(this,this._el_33,throwOnChange)) { this._appEl_33.componentView.markAsCheckOnce(); }
    this._Header_35_3.detectChangesInternal(this,this._el_35,throwOnChange);
    if (this._Toolbar_37_4.detectChangesInternal(this,this._el_37,throwOnChange)) { this._appEl_37.componentView.markAsCheckOnce(); }
    if (this._ToolbarTitle_39_4.detectChangesInternal(this,this._el_39,throwOnChange)) { this._appEl_39.componentView.markAsCheckOnce(); }
    if (this._Content_44_4.detectChangesInternal(this,this._el_44,throwOnChange)) { this._appEl_44.componentView.markAsCheckOnce(); }
    this._List_46_3.detectChangesInternal(this,this._el_46,throwOnChange);
    if (this._Item_48_4.detectChangesInternal(this,this._el_48,throwOnChange)) { this._appEl_48.componentView.markAsCheckOnce(); }
    this._ListHeader_48_5.detectChangesInternal(this,this._el_48,throwOnChange);
    const currVal_10:any = this.context.appPages;
    this._NgFor_51_6.check_ngForOf(currVal_10,throwOnChange,false);
    this._NgFor_51_6.detectChangesInternal(this,this._anchor_51,throwOnChange);
    this._List_54_3.detectChangesInternal(this,this._el_54,throwOnChange);
    if (this._Item_56_4.detectChangesInternal(this,this._el_56,throwOnChange)) { this._appEl_56.componentView.markAsCheckOnce(); }
    this._ListHeader_56_5.detectChangesInternal(this,this._el_56,throwOnChange);
    const currVal_11:any = this.context.loggedInPages;
    this._NgFor_59_6.check_ngForOf(currVal_11,throwOnChange,false);
    this._NgFor_59_6.detectChangesInternal(this,this._anchor_59,throwOnChange);
    const currVal_12:any = this.context.rootPage;
    this._Nav_65_4.check_root(currVal_12,throwOnChange,false);
    const currVal_13:any = 'false';
    this._Nav_65_4.check_swipeBackEnabled(currVal_13,throwOnChange,false);
    this._Nav_65_4.detectChangesInternal(this,this._el_65,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_16_1.dirty) {
        this._query_Button_16_1.reset(([] as any[]));
        this._Item_16_4.context._buttons = this._query_Button_16_1;
        this._query_Button_16_1.notifyOnChanges();
      }
      if (this._query_Icon_16_2.dirty) {
        this._query_Icon_16_2.reset(([] as any[]));
        this._Item_16_4.context._icons = this._query_Icon_16_2;
        this._query_Icon_16_2.notifyOnChanges();
      }
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset(([] as any[]));
        this._Item_24_4.context._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset(([] as any[]));
        this._Item_24_4.context._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if (this._query_Button_48_1.dirty) {
        this._query_Button_48_1.reset(([] as any[]));
        this._Item_48_4.context._buttons = this._query_Button_48_1;
        this._query_Button_48_1.notifyOnChanges();
      }
      if (this._query_Icon_48_2.dirty) {
        this._query_Icon_48_2.reset(([] as any[]));
        this._Item_48_4.context._icons = this._query_Icon_48_2;
        this._query_Icon_48_2.notifyOnChanges();
      }
      if (this._query_Button_56_1.dirty) {
        this._query_Button_56_1.reset(([] as any[]));
        this._Item_56_4.context._buttons = this._query_Button_56_1;
        this._query_Button_56_1.notifyOnChanges();
      }
      if (this._query_Icon_56_2.dirty) {
        this._query_Icon_56_2.reset(([] as any[]));
        this._Item_56_4.context._icons = this._query_Icon_56_2;
        this._query_Icon_56_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_16_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_24_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_48_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_56_4.context.ngAfterContentInit(); }
    }
    const currVal_2:any = this._Toolbar_5_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_5,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_12_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_12,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_8:any = this._Toolbar_37_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_37,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._Content_44_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_44,'statusbar-padding',currVal_9);
      this._expr_9 = currVal_9;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_65_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_12_4.context.ngOnDestroy();
    this._Menu_1_4.context.ngOnDestroy();
    this._Content_44_4.context.ngOnDestroy();
    this._Menu_33_4.context.ngOnDestroy();
  }
}
export function viewFactory_ConferenceApp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ConferenceApp> {
  if ((renderType_ConferenceApp === (null as any))) { (renderType_ConferenceApp = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_ConferenceApp,{})); }
  return new _View_ConferenceApp0(viewUtils,parentInjector,declarationEl);
}
class _View_ConferenceApp1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import21.Wrapper_Item;
  _ItemContent_0_5:import21.Wrapper_ItemContent;
  _MenuClose_0_6:import50.Wrapper_MenuClose;
  _query_Label_0_0:import15.QueryList<any>;
  _query_Button_0_1:import15.QueryList<any>;
  _query_Icon_0_2:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import51.Wrapper_Icon;
  _text_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConferenceApp1,renderType_ConferenceApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Wrapper_Item(this.parent.parentInjector.get(import34.Form),this.parent.parentInjector.get(import26.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.Wrapper_ItemContent();
    this._MenuClose_0_6 = new import50.Wrapper_MenuClose(this.parent.parentInjector.get(import10.MenuController));
    this._query_Label_0_0 = new import15.QueryList<any>();
    this._query_Button_0_1 = new import15.QueryList<any>();
    this._query_Icon_0_2 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import51.Wrapper_Icon(this.parent.parentInjector.get(import26.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import52.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3.context; }
    if (((token === import43.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_0_4.context; }
    if (((token === import43.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_0_5.context; }
    if (((token === import53.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuClose_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_2:any = '';
    this._MenuClose_0_6.check_menuClose(currVal_2,throwOnChange,false);
    this._MenuClose_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_3:any = this.context.$implicit.icon;
    this._Icon_2_3.check_name(currVal_3,throwOnChange,false);
    this._Icon_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3.context]);
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.context.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_ConferenceApp1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ConferenceApp1(viewUtils,parentInjector,declarationEl);
}
class _View_ConferenceApp2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import21.Wrapper_Item;
  _ItemContent_0_5:import21.Wrapper_ItemContent;
  _MenuClose_0_6:import50.Wrapper_MenuClose;
  _query_Label_0_0:import15.QueryList<any>;
  _query_Button_0_1:import15.QueryList<any>;
  _query_Icon_0_2:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import51.Wrapper_Icon;
  _text_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConferenceApp2,renderType_ConferenceApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Wrapper_Item(this.parent.parentInjector.get(import34.Form),this.parent.parentInjector.get(import26.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.Wrapper_ItemContent();
    this._MenuClose_0_6 = new import50.Wrapper_MenuClose(this.parent.parentInjector.get(import10.MenuController));
    this._query_Label_0_0 = new import15.QueryList<any>();
    this._query_Button_0_1 = new import15.QueryList<any>();
    this._query_Icon_0_2 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import51.Wrapper_Icon(this.parent.parentInjector.get(import26.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import52.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3.context; }
    if (((token === import43.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_0_4.context; }
    if (((token === import43.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_0_5.context; }
    if (((token === import53.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuClose_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_2:any = '';
    this._MenuClose_0_6.check_menuClose(currVal_2,throwOnChange,false);
    this._MenuClose_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_3:any = this.context.$implicit.icon;
    this._Icon_2_3.check_name(currVal_3,throwOnChange,false);
    this._Icon_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3.context]);
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.context.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_ConferenceApp2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ConferenceApp2(viewUtils,parentInjector,declarationEl);
}
class _View_ConferenceApp3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import21.Wrapper_Item;
  _ItemContent_0_5:import21.Wrapper_ItemContent;
  _MenuClose_0_6:import50.Wrapper_MenuClose;
  _query_Label_0_0:import15.QueryList<any>;
  _query_Button_0_1:import15.QueryList<any>;
  _query_Icon_0_2:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import51.Wrapper_Icon;
  _text_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConferenceApp3,renderType_ConferenceApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Wrapper_Item(this.parent.parentInjector.get(import34.Form),this.parent.parentInjector.get(import26.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.Wrapper_ItemContent();
    this._MenuClose_0_6 = new import50.Wrapper_MenuClose(this.parent.parentInjector.get(import10.MenuController));
    this._query_Label_0_0 = new import15.QueryList<any>();
    this._query_Button_0_1 = new import15.QueryList<any>();
    this._query_Icon_0_2 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import51.Wrapper_Icon(this.parent.parentInjector.get(import26.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import52.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3.context; }
    if (((token === import43.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_0_4.context; }
    if (((token === import43.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_0_5.context; }
    if (((token === import53.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuClose_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_2:any = '';
    this._MenuClose_0_6.check_menuClose(currVal_2,throwOnChange,false);
    this._MenuClose_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_3:any = this.context.$implicit.icon;
    this._Icon_2_3.check_name(currVal_3,throwOnChange,false);
    this._Icon_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3.context]);
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.context.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_ConferenceApp3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ConferenceApp3(viewUtils,parentInjector,declarationEl);
}
class _View_ConferenceApp4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import21.Wrapper_Item;
  _ItemContent_0_5:import21.Wrapper_ItemContent;
  _MenuClose_0_6:import50.Wrapper_MenuClose;
  _query_Label_0_0:import15.QueryList<any>;
  _query_Button_0_1:import15.QueryList<any>;
  _query_Icon_0_2:import15.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import51.Wrapper_Icon;
  _text_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConferenceApp4,renderType_ConferenceApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Wrapper_Item(this.parent.parentInjector.get(import34.Form),this.parent.parentInjector.get(import26.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.Wrapper_ItemContent();
    this._MenuClose_0_6 = new import50.Wrapper_MenuClose(this.parent.parentInjector.get(import10.MenuController));
    this._query_Label_0_0 = new import15.QueryList<any>();
    this._query_Button_0_1 = new import15.QueryList<any>();
    this._query_Icon_0_2 = new import15.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import51.Wrapper_Icon(this.parent.parentInjector.get(import26.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import52.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3.context; }
    if (((token === import43.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Item_0_4.context; }
    if (((token === import43.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ItemContent_0_5.context; }
    if (((token === import53.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._MenuClose_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_2:any = '';
    this._MenuClose_0_6.check_menuClose(currVal_2,throwOnChange,false);
    this._MenuClose_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_3:any = this.context.$implicit.icon;
    this._Icon_2_3.check_name(currVal_3,throwOnChange,false);
    this._Icon_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3.context]);
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.context.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_ConferenceApp4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ConferenceApp4(viewUtils,parentInjector,declarationEl);
}