/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './director-list';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import9 from 'ionic-angular/navigation/nav-controller';
import * as import10 from '../../providers/conference-data';
import * as import11 from 'ionic-angular/config/config';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import19 from '@angular/core/src/linker/query_list';
import * as import20 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import23 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from 'ionic-angular/navigation/view-controller';
import * as import26 from 'ionic-angular/components/app/app';
import * as import27 from 'ionic-angular/components/menu/menu-controller';
import * as import28 from 'ionic-angular/components/toolbar/toolbar';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/components/tabs/tabs';
import * as import32 from '@angular/core/src/linker/template_ref';
import * as import33 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import34 from 'ionic-angular/components/icon/icon';
import * as import35 from 'ionic-angular/components/button/button';
import * as import36 from 'ionic-angular/components/menu/menu-toggle';
import * as import37 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import38 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import39 from 'ionic-angular/components/navbar/navbar';
import * as import40 from '@angular/common/src/directives/ng_for';
import * as import41 from 'ionic-angular/components/content/content';
import * as import42 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import43 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import44 from '../../node_modules/ionic-angular/components/avatar/avatar.ngfactory';
import * as import45 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import46 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import47 from 'ionic-angular/util/form';
import * as import48 from 'ionic-angular/gestures/gesture-controller';
import * as import49 from 'ionic-angular/components/avatar/avatar';
import * as import50 from 'ionic-angular/components/item/item';
import * as import51 from 'ionic-angular/components/card/card';
import * as import52 from 'ionic-angular/components/list/list';
import * as import53 from 'ionic-angular/components/grid/grid';
import * as import54 from '@angular/core/src/security';
export class Wrapper_DirectorListPage {
  context:import0.DirectorListPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this.changed = false;
    this.context = new import0.DirectorListPage(p0,p1,p2,p3);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_DirectorListPage_Host:import2.RenderComponentType = (null as any);
class _View_DirectorListPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _DirectorListPage_0_4:Wrapper_DirectorListPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DirectorListPage_Host0,renderType_DirectorListPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-director-list',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DirectorListPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DirectorListPage_0_4 = new Wrapper_DirectorListPage(this.parentInjector.get(import8.ActionSheetController),this.parentInjector.get(import9.NavController),this.parentInjector.get(import10.ConferenceData),this.parentInjector.get(import11.Config));
    this._appEl_0.initComponent(this._DirectorListPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._DirectorListPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.DirectorListPage) && (0 === requestNodeIndex))) { return this._DirectorListPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._DirectorListPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DirectorListPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_DirectorListPage_Host === (null as any))) { (renderType_DirectorListPage_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_DirectorListPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const DirectorListPageNgFactory:import13.ComponentFactory<import0.DirectorListPage> = new import13.ComponentFactory<import0.DirectorListPage>('page-director-list',viewFactory_DirectorListPage_Host0,import0.DirectorListPage);
const styles_DirectorListPage:any[] = ([] as any[]);
var renderType_DirectorListPage:import2.RenderComponentType = (null as any);
class _View_DirectorListPage0 extends import1.AppView<import0.DirectorListPage> {
  _el_0:any;
  _Header_0_3:import14.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import15.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import16.Wrapper_Button;
  _MenuToggle_4_5:import17.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import18.Wrapper_ToolbarItem;
  _query_Button_4_0:import19.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import20.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import21.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Content_14_4:import22.Wrapper_Content;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _TemplateRef_16_5:any;
  _NgFor_16_6:import23.Wrapper_NgFor;
  _text_17:any;
  _text_18:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DirectorListPage0,renderType_DirectorListPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import14.Wrapper_Header(this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import25.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import15.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import15.Wrapper_Navbar(this.parentInjector.get(import26.App),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import9.NavController,(null as any)),this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import16.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import16.Wrapper_Button('','',this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import17.Wrapper_MenuToggle(this.parentInjector.get(import27.MenuController),new import24.ElementRef(this._el_4),this.parentInjector.get(import25.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import18.Wrapper_ToolbarItem(this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import19.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import20.Wrapper_Icon(this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import21.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import21.Wrapper_ToolbarTitle(this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Directors',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','outer-content speaker-list');
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import22.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import22.Wrapper_Content(this.parentInjector.get(import11.Config),new import24.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import26.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import31.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_16 = new import3.AppElement(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import32.TemplateRef_(this._appEl_16,viewFactory_DirectorListPage1);
    this._NgFor_16_6 = new import23.Wrapper_NgFor(this._appEl_16.vcRef,this._TemplateRef_16_5,this.parentInjector.get(import33.IterableDiffers),this.ref);
    this._text_17 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._appEl_16,
        this._text_17
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import34.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import35.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import36.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import37.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import38.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import39.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4.context; }
    if (((token === import28.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import32.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import40.NgFor) && (16 === requestNodeIndex))) { return this._NgFor_16_6.context; }
    if (((token === import41.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Content_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_6_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Content_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    const currVal_8:any = this.context.directors;
    this._NgFor_16_6.check_ngForOf(currVal_8,throwOnChange,false);
    this._NgFor_16_6.detectChangesInternal(this,this._anchor_16,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Content_14_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_DirectorListPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.DirectorListPage> {
  if ((renderType_DirectorListPage === (null as any))) { (renderType_DirectorListPage = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_DirectorListPage,{})); }
  return new _View_DirectorListPage0(viewUtils,parentInjector,declarationEl);
}
class _View_DirectorListPage1 extends import1.AppView<any> {
  _el_0:any;
  _Card_0_3:import42.Wrapper_Card;
  _text_1:any;
  _el_2:any;
  _CardHeader_2_3:import42.Wrapper_CardHeader;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Item_4_4:import43.Wrapper_Item;
  _ItemContent_4_5:import43.Wrapper_ItemContent;
  _query_Label_4_0:import19.QueryList<any>;
  _query_Button_4_1:import19.QueryList<any>;
  _query_Icon_4_2:import19.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Avatar_6_3:import44.Wrapper_Avatar;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _CardContent_13_3:import42.Wrapper_CardContent;
  _text_14:any;
  _el_15:any;
  _List_15_3:import45.Wrapper_List;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _TemplateRef_17_5:any;
  _NgFor_17_6:import23.Wrapper_NgFor;
  _text_18:any;
  _el_19:any;
  /*private*/ _appEl_19:import3.AppElement;
  _Item_19_4:import43.Wrapper_Item;
  _ItemContent_19_5:import43.Wrapper_ItemContent;
  _query_Label_19_0:import19.QueryList<any>;
  _query_Button_19_1:import19.QueryList<any>;
  _query_Icon_19_2:import19.QueryList<any>;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _Row_27_3:import46.Wrapper_Row;
  _text_28:any;
  _el_29:any;
  _Col_29_3:import46.Wrapper_Col;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import3.AppElement;
  _Button_31_4:import16.Wrapper_Button;
  _text_32:any;
  _el_33:any;
  _Icon_33_3:import20.Wrapper_Icon;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _Col_37_3:import46.Wrapper_Col;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import3.AppElement;
  _Button_39_4:import16.Wrapper_Button;
  _text_40:any;
  _el_41:any;
  _Icon_41_3:import20.Wrapper_Icon;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _Col_45_3:import46.Wrapper_Col;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import3.AppElement;
  _Button_47_4:import16.Wrapper_Button;
  _text_48:any;
  _el_49:any;
  _Icon_49_3:import20.Wrapper_Icon;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_23:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DirectorListPage1,renderType_DirectorListPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','speaker-card');
    this._Card_0_3 = new import42.Wrapper_Card(this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card-header',(null as any));
    this._CardHeader_2_3 = new import42.Wrapper_CardHeader();
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','item item-block');
    this.renderer.setElementAttribute(this._el_4,'detail-none','');
    this.renderer.setElementAttribute(this._el_4,'ion-item','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import43.viewFactory_Item0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Item_4_4 = new import43.Wrapper_Item(this.parent.parentInjector.get(import47.Form),this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_4),this.renderer);
    this._ItemContent_4_5 = new import43.Wrapper_ItemContent();
    this._query_Label_4_0 = new import19.QueryList<any>();
    this._query_Button_4_1 = new import19.QueryList<any>();
    this._query_Icon_4_2 = new import19.QueryList<any>();
    this._appEl_4.initComponent(this._Item_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-avatar',(null as any));
    this.renderer.setElementAttribute(this._el_6,'item-left','');
    this._Avatar_6_3 = new import44.Wrapper_Avatar();
    this._text_7 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'img',(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_10 = this.renderer.createText((null as any),'',(null as any));
    this._query_Label_4_0.reset(([] as any[]));
    this._Item_4_4.context.contentLabel = this._query_Label_4_0.first;
    compView_4.create(this._Item_4_4.context,[
      ([] as any[]).concat([this._el_6]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_5,
        this._text_10
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_0,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','outer-content');
    this._CardContent_13_3 = new import42.Wrapper_CardContent();
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-list',(null as any));
    this._List_15_3 = new import45.Wrapper_List(this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_15),this.renderer,this.parent.parentInjector.get(import48.GestureController));
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._appEl_17 = new import3.AppElement(17,15,this,this._anchor_17);
    this._TemplateRef_17_5 = new import32.TemplateRef_(this._appEl_17,viewFactory_DirectorListPage2);
    this._NgFor_17_6 = new import23.Wrapper_NgFor(this._appEl_17.vcRef,this._TemplateRef_17_5,this.parent.parentInjector.get(import33.IterableDiffers),this.parent.ref);
    this._text_18 = this.renderer.createText(this._el_15,'\n\n        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_15,'button',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','item item-block');
    this.renderer.setElementAttribute(this._el_19,'ion-item','');
    this._appEl_19 = new import3.AppElement(19,15,this,this._el_19);
    var compView_19:any = import43.viewFactory_Item0(this.viewUtils,this.injector(19),this._appEl_19);
    this._Item_19_4 = new import43.Wrapper_Item(this.parent.parentInjector.get(import47.Form),this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_19),this.renderer);
    this._ItemContent_19_5 = new import43.Wrapper_ItemContent();
    this._query_Label_19_0 = new import19.QueryList<any>();
    this._query_Button_19_1 = new import19.QueryList<any>();
    this._query_Icon_19_2 = new import19.QueryList<any>();
    this._appEl_19.initComponent(this._Item_19_4.context,([] as any[]),compView_19);
    this._text_20 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_19_0.reset(([] as any[]));
    this._Item_19_4.context.contentLabel = this._query_Label_19_0.first;
    compView_19.create(this._Item_19_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_20,
        this._el_21,
        this._text_23
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(this._el_15,'\n      ',(null as any));
    this._text_25 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_27,'no-padding','');
    this._Row_27_3 = new import46.Wrapper_Row();
    this._text_28 = this.renderer.createText(this._el_27,'\n      ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'ion-col',(null as any));
    this._Col_29_3 = new import46.Wrapper_Col();
    this._text_30 = this.renderer.createText(this._el_29,'\n        ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'button',(null as any));
    this.renderer.setElementAttribute(this._el_31,'clear','');
    this.renderer.setElementAttribute(this._el_31,'color','primary');
    this.renderer.setElementAttribute(this._el_31,'icon-left','');
    this.renderer.setElementAttribute(this._el_31,'ion-button','');
    this.renderer.setElementAttribute(this._el_31,'small','');
    this._appEl_31 = new import3.AppElement(31,29,this,this._el_31);
    var compView_31:any = import16.viewFactory_Button0(this.viewUtils,this.injector(31),this._appEl_31);
    this._Button_31_4 = new import16.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_31),this.renderer);
    this._appEl_31.initComponent(this._Button_31_4.context,([] as any[]),compView_31);
    this._text_32 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_33,'name','logo-twitter');
    this.renderer.setElementAttribute(this._el_33,'role','img');
    this._Icon_33_3 = new import20.Wrapper_Icon(this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_33),this.renderer);
    this._text_34 = this.renderer.createText((null as any),'\n          Tweet\n        ',(null as any));
      compView_31.create(this._Button_31_4.context,[([] as any[]).concat([
        this._text_32,
        this._el_33,
        this._text_34
      ]
    )],(null as any));
    this._text_35 = this.renderer.createText(this._el_29,'\n      ',(null as any));
    this._text_36 = this.renderer.createText(this._el_27,'\n      ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_27,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_37,'text-center','');
    this._Col_37_3 = new import46.Wrapper_Col();
    this._text_38 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'button',(null as any));
    this.renderer.setElementAttribute(this._el_39,'clear','');
    this.renderer.setElementAttribute(this._el_39,'color','primary');
    this.renderer.setElementAttribute(this._el_39,'icon-left','');
    this.renderer.setElementAttribute(this._el_39,'ion-button','');
    this.renderer.setElementAttribute(this._el_39,'small','');
    this._appEl_39 = new import3.AppElement(39,37,this,this._el_39);
    var compView_39:any = import16.viewFactory_Button0(this.viewUtils,this.injector(39),this._appEl_39);
    this._Button_39_4 = new import16.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_39),this.renderer);
    this._appEl_39.initComponent(this._Button_39_4.context,([] as any[]),compView_39);
    this._text_40 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_41,'name','share-alt');
    this.renderer.setElementAttribute(this._el_41,'role','img');
    this._Icon_41_3 = new import20.Wrapper_Icon(this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_41),this.renderer);
    this._text_42 = this.renderer.createText((null as any),'\n         Share\n        ',(null as any));
      compView_39.create(this._Button_39_4.context,[([] as any[]).concat([
        this._text_40,
        this._el_41,
        this._text_42
      ]
    )],(null as any));
    this._text_43 = this.renderer.createText(this._el_37,'\n      ',(null as any));
    this._text_44 = this.renderer.createText(this._el_27,'\n      ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_27,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_45,'text-right','');
    this._Col_45_3 = new import46.Wrapper_Col();
    this._text_46 = this.renderer.createText(this._el_45,'\n        ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'button',(null as any));
    this.renderer.setElementAttribute(this._el_47,'clear','');
    this.renderer.setElementAttribute(this._el_47,'color','primary');
    this.renderer.setElementAttribute(this._el_47,'icon-left','');
    this.renderer.setElementAttribute(this._el_47,'ion-button','');
    this.renderer.setElementAttribute(this._el_47,'small','');
    this._appEl_47 = new import3.AppElement(47,45,this,this._el_47);
    var compView_47:any = import16.viewFactory_Button0(this.viewUtils,this.injector(47),this._appEl_47);
    this._Button_47_4 = new import16.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_47),this.renderer);
    this._appEl_47.initComponent(this._Button_47_4.context,([] as any[]),compView_47);
    this._text_48 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_49 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_49,'name','chatboxes');
    this.renderer.setElementAttribute(this._el_49,'role','img');
    this._Icon_49_3 = new import20.Wrapper_Icon(this.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_49),this.renderer);
    this._text_50 = this.renderer.createText((null as any),'\n          Contact\n        ',(null as any));
      compView_47.create(this._Button_47_4.context,[([] as any[]).concat([
        this._text_48,
        this._el_49,
        this._text_50
      ]
    )],(null as any));
    this._text_51 = this.renderer.createText(this._el_45,'\n      ',(null as any));
    this._text_52 = this.renderer.createText(this._el_27,'\n    ',(null as any));
    this._text_53 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_31,'click',this.eventHandler(this._handle_click_31_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_39,'click',this.eventHandler(this._handle_click_39_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_47,'click',this.eventHandler(this._handle_click_47_0.bind(this)));
    this._expr_23 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import49.Avatar) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Avatar_6_3.context; }
    if (((token === import50.Item) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Item_4_4.context; }
    if (((token === import50.ItemContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ItemContent_4_5.context; }
    if (((token === import51.CardHeader) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._CardHeader_2_3.context; }
    if (((token === import32.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import40.NgFor) && (17 === requestNodeIndex))) { return this._NgFor_17_6.context; }
    if (((token === import50.Item) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Item_19_4.context; }
    if (((token === import50.ItemContent) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._ItemContent_19_5.context; }
    if (((token === import52.List) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._List_15_3.context; }
    if (((token === import51.CardContent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._CardContent_13_3.context; }
    if (((token === import34.Icon) && (33 === requestNodeIndex))) { return this._Icon_33_3.context; }
    if (((token === import35.Button) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Button_31_4.context; }
    if (((token === import53.Col) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Col_29_3.context; }
    if (((token === import34.Icon) && (41 === requestNodeIndex))) { return this._Icon_41_3.context; }
    if (((token === import35.Button) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Button_39_4.context; }
    if (((token === import53.Col) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Col_37_3.context; }
    if (((token === import34.Icon) && (49 === requestNodeIndex))) { return this._Icon_49_3.context; }
    if (((token === import35.Button) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Button_47_4.context; }
    if (((token === import53.Col) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Col_45_3.context; }
    if (((token === import53.Row) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Row_27_3.context; }
    if (((token === import51.Card) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Card_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Card_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._CardHeader_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Item_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    this._ItemContent_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._Avatar_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    this._CardContent_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._List_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    const currVal_3:any = this.context.$implicit.sessions;
    this._NgFor_17_6.check_ngForOf(currVal_3,throwOnChange,false);
    this._NgFor_17_6.detectChangesInternal(this,this._anchor_17,throwOnChange);
    if (this._Item_19_4.detectChangesInternal(this,this._el_19,throwOnChange)) { this._appEl_19.componentView.markAsCheckOnce(); }
    this._ItemContent_19_5.detectChangesInternal(this,this._el_19,throwOnChange);
    this._Row_27_3.detectChangesInternal(this,this._el_27,throwOnChange);
    this._Col_29_3.detectChangesInternal(this,this._el_29,throwOnChange);
    const currVal_7:any = '';
    this._Button_31_4.check_small(currVal_7,throwOnChange,false);
    const currVal_8:any = '';
    this._Button_31_4.check_clear(currVal_8,throwOnChange,false);
    const currVal_9:any = 'primary';
    this._Button_31_4.check_color(currVal_9,throwOnChange,false);
    if (this._Button_31_4.detectChangesInternal(this,this._el_31,throwOnChange)) { this._appEl_31.componentView.markAsCheckOnce(); }
    const currVal_10:any = 'logo-twitter';
    this._Icon_33_3.check_name(currVal_10,throwOnChange,false);
    this._Icon_33_3.detectChangesInternal(this,this._el_33,throwOnChange);
    this._Col_37_3.detectChangesInternal(this,this._el_37,throwOnChange);
    const currVal_13:any = '';
    this._Button_39_4.check_small(currVal_13,throwOnChange,false);
    const currVal_14:any = '';
    this._Button_39_4.check_clear(currVal_14,throwOnChange,false);
    const currVal_15:any = 'primary';
    this._Button_39_4.check_color(currVal_15,throwOnChange,false);
    if (this._Button_39_4.detectChangesInternal(this,this._el_39,throwOnChange)) { this._appEl_39.componentView.markAsCheckOnce(); }
    const currVal_16:any = 'share-alt';
    this._Icon_41_3.check_name(currVal_16,throwOnChange,false);
    this._Icon_41_3.detectChangesInternal(this,this._el_41,throwOnChange);
    this._Col_45_3.detectChangesInternal(this,this._el_45,throwOnChange);
    const currVal_19:any = '';
    this._Button_47_4.check_small(currVal_19,throwOnChange,false);
    const currVal_20:any = '';
    this._Button_47_4.check_clear(currVal_20,throwOnChange,false);
    const currVal_21:any = 'primary';
    this._Button_47_4.check_color(currVal_21,throwOnChange,false);
    if (this._Button_47_4.detectChangesInternal(this,this._el_47,throwOnChange)) { this._appEl_47.componentView.markAsCheckOnce(); }
    const currVal_22:any = 'chatboxes';
    this._Icon_49_3.check_name(currVal_22,throwOnChange,false);
    this._Icon_49_3.detectChangesInternal(this,this._el_49,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_1.dirty) {
        this._query_Button_4_1.reset(([] as any[]));
        this._Item_4_4.context._buttons = this._query_Button_4_1;
        this._query_Button_4_1.notifyOnChanges();
      }
      if (this._query_Icon_4_2.dirty) {
        this._query_Icon_4_2.reset(([] as any[]));
        this._Item_4_4.context._icons = this._query_Icon_4_2;
        this._query_Icon_4_2.notifyOnChanges();
      }
      if (this._query_Button_19_1.dirty) {
        this._query_Button_19_1.reset(([] as any[]));
        this._Item_19_4.context._buttons = this._query_Button_19_1;
        this._query_Button_19_1.notifyOnChanges();
      }
      if (this._query_Icon_19_2.dirty) {
        this._query_Icon_19_2.reset(([] as any[]));
        this._Item_19_4.context._icons = this._query_Icon_19_2;
        this._query_Icon_19_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_4_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_19_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_31_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_39_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_47_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this.context.$implicit.profilePic;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_8,'src',this.viewUtils.sanitizer.sanitize(import54.SecurityContext.URL,currVal_1));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'\n        ',this.context.$implicit.name,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_10,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = import4.interpolate(1,'About ',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_22,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_11:any = this._Icon_33_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_33,'hide',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_17:any = this._Icon_41_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_41,'hide',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_23:any = this._Icon_49_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_49,'hide',currVal_23);
      this._expr_23 = currVal_23;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_33_3.context.ngOnDestroy();
    this._Icon_41_3.context.ngOnDestroy();
    this._Icon_49_3.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.goToDirectorDetail(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.goToSpeakerDetail(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_31_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.goToDirectorTwitter(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_39_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openDirectorShare(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_47_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openContact(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_DirectorListPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_DirectorListPage1(viewUtils,parentInjector,declarationEl);
}
class _View_DirectorListPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import43.Wrapper_Item;
  _ItemContent_0_5:import43.Wrapper_ItemContent;
  _query_Label_0_0:import19.QueryList<any>;
  _query_Button_0_1:import19.QueryList<any>;
  _query_Icon_0_2:import19.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_DirectorListPage2,renderType_DirectorListPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import43.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import43.Wrapper_Item(this.parent.parent.parentInjector.get(import47.Form),this.parent.parent.parentInjector.get(import11.Config),new import24.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import43.Wrapper_ItemContent();
    this._query_Label_0_0 = new import19.QueryList<any>();
    this._query_Button_0_1 = new import19.QueryList<any>();
    this._query_Icon_0_2 = new import19.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import50.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Item_0_4.context; }
    if (((token === import50.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_3,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.goToSessionDetail(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_DirectorListPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_DirectorListPage2(viewUtils,parentInjector,declarationEl);
}